In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.metrics import mean_squared_error, r2_score

In [21]:
df=pd.read_csv('/content/cloud_scaling_dataset.csv')

In [22]:
df

,CPU_Utilization,Memory_Usage,Request_Rate,Response_Latency,Queue_Length,Scaling_Action
0,36.1,50.0,362,108,6,Normal
1,40.1,52.9,530,127,35,Normal
2,28.6,30.2,377,62,3,Normal
3,59.0,61.5,981,311,76,Moderate
4,85.9,72.6,1629,724,142,High
...,...,...,...,...,...,...
3495,22.8,37.5,160,69,8,Normal
3496,47.9,46.1,700,137,36,Moderate
3497,85.5,77.6,1452,797,146,Moderate
3498,39.7,38.1,509,126,10,Normal
3499,69.8,66.7,1030,402,86,Moderate

In [23]:
df.head()

,CPU_Utilization,Memory_Usage,Request_Rate,Response_Latency,Queue_Length,Scaling_Action
0,36.1,50.0,362,108,6,Normal
1,40.1,52.9,530,127,35,Normal
2,28.6,30.2,377,62,3,Normal
3,59.0,61.5,981,311,76,Moderate
4,85.9,72.6,1629,724,142,High

In [24]:
df.tail()

,CPU_Utilization,Memory_Usage,Request_Rate,Response_Latency,Queue_Length,Scaling_Action
3495,22.8,37.5,160,69,8,Normal
3496,47.9,46.1,700,137,36,Moderate
3497,85.5,77.6,1452,797,146,Moderate
3498,39.7,38.1,509,126,10,Normal
3499,69.8,66.7,1030,402,86,Moderate

In [25]:
df.describe()

,CPU_Utilization,Memory_Usage,Request_Rate,Response_Latency,Queue_Length
count,3500.000000,3500.000000,3500.000000,3500.000000,3500.000000
mean,45.200686,48.466857,644.298857,233.843714,44.706571
std,24.646282,16.166323,480.557885,234.474241,47.626325
min,2.000000,12.200000,5.000000,20.000000,0.000000
25%,22.900000,35.800000,217.000000,65.000000,7.000000
50%,42.450000,46.600000,542.000000,126.000000,26.000000
75%,64.900000,61.100000,1007.000000,332.250000,71.000000
max,99.100000,93.900000,1774.000000,1047.000000,186.000000

In [34]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix,accuracy_score

In [35]:
xx = ['CPU_Utilization', 'Memory_Usage', 'Request_Rate', 'Response_Latency', 'Queue_Length']
x = df[xx]
y = df['Scaling_Action']

In [36]:
le=LabelEncoder()
model=DecisionTreeClassifier()

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [38]:
model.fit(x_train, y_train)

DecisionTreeClassifier()

In [39]:
y_pred = model.predict(x_test)

In [40]:
acc=accuracy_score(y_test, y_pred)
acc

0.82

In [44]:
u1=float(input("Enter the CPU Utilization: "))
u2=float(input("Enter the Memory Usage: "))
u3=float(input("Enter the Request Rate: "))
u4=float(input("Enter the Response Latency: "))
u5=float(input("Enter the Queue Length: "))
user=pd.DataFrame({'CPU_Utilization':[u1],
                   'Memory_Usage':[u2],
                   'Request_Rate':[u3],
                   'Response_Latency':[u4],
                   'Queue_Length':[u5]})
Prediction=model.predict(user)
print("The Scaling Action is: ",Prediction)

Enter the CPU Utilization: 22
Enter the Memory Usage: 37
Enter the Request Rate: 120
Enter the Response Latency: 76
Enter the Queue Length: 45
The Scaling Action is:  ['Normal']