In [1]:
# stock market movement using ----multinomial navie base
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB

In [2]:
df=pd.read_csv('/content/news_article_multinomial_nb_3000.csv')
df

      article_id                                            article   category
0              1  Officials said Kylian Mbappe recorded a centur...     Sports
1              2  A recent report said the Prime Minister announ...  Political
2              3  In the latest update, LeBron James recorded a ...     Sports
3              4  According to a new report, NASA launched a spa...      Space
4              5  In a latest development, crime branch officers...      Crime
...          ...                                                ...        ...
2995        2996  A recent report said Indian space scientists a...      Space
2996        2997  In the latest update, NASA scientists launched...      Space
2997        2998  Officials said the Parliament presented a budg...  Political
2998        2999  According to a new report, members of parliame...  Political
2999        3000  In the latest update, NASA scientists launched...      Space

[3000 rows x 3 columns]

In [3]:
df.head()

   article_id                                            article   category
0           1  Officials said Kylian Mbappe recorded a centur...     Sports
1           2  A recent report said the Prime Minister announ...  Political
2           3  In the latest update, LeBron James recorded a ...     Sports
3           4  According to a new report, NASA launched a spa...      Space
4           5  In a latest development, crime branch officers...      Crime

In [4]:
df.tail()

      article_id                                            article   category
2995        2996  A recent report said Indian space scientists a...      Space
2996        2997  In the latest update, NASA scientists launched...      Space
2997        2998  Officials said the Parliament presented a budg...  Political
2998        2999  According to a new report, members of parliame...  Political
2999        3000  In the latest update, NASA scientists launched...      Space

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   article_id  3000 non-null   int64
 1   article     3000 non-null   object
 2   category    3000 non-null   object
dtypes: int64(1), object(2)
memory usage: 70.4+ KB

In [6]:
df.describe()

        article_id
count  3000.000000
mean   1500.500000
std     866.169729
min       1.000000
25%     750.750000
50%    1500.500000
75%    2250.250000
max    3000.000000

In [7]:
df.isnull().sum()

article_id    0
article       0
category      0
dtype: int64

In [9]:
x=df['article']
y=df['category']
m=MultinomialNB()
le=LabelEncoder()

In [10]:
y_val=le.fit_transform(y)

In [17]:
x = df['article']
vector = CountVectorizer()
x_val = vector.fit_transform(x)

In [19]:
m.fit(x_val, y_val)

MultinomialNB()

In [ ]:
while True:
    content=input('enter the article content:')
    test=vector.transform([content])
    predict=m.predict(test)
    print('predicted news:',le.inverse_transform(predict)[0])

enter the article content:earth
predicted news: Geography
enter the article content:moon
predicted news: Cinema
enter the article content:mars
predicted news: Space
enter the article content:ms subhulakshmi
predicted news: Sports

In [ ]:
acc=accuracy_score(y_val,m.predict(x_val))
print('accuracy score:',acc)