In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/content/product_demand_forecasting_3000_rows.csv')
df

,Date,Store_ID,Product_ID,Product_Name,Category,Price,Discount_Percent,Advertising_Spend,Holiday_Flag,Weekend_Flag,Stock_Available,Previous_Day_Sales,Units_Sold
0,2021-01-01,ST001,P001,Rice 5kg,Grocery,659.32,0,174.34,0,0,44,15,12
1,2021-01-02,ST001,P001,Rice 5kg,Grocery,591.69,10,32.03,0,1,28,12,14
2,2021-01-03,ST001,P001,Rice 5kg,Grocery,661.10,0,160.97,0,1,94,14,14
3,2021-01-04,ST001,P001,Rice 5kg,Grocery,606.73,5,206.91,0,0,79,14,15
4,2021-01-05,ST001,P001,Rice 5kg,Grocery,581.60,10,242.67,0,0,79,15,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2021-02-25,ST005,P010,Notebook,Stationery,38.73,15,89.81,0,0,135,30,34
2996,2021-02-26,ST005,P010,Notebook,Stationery,35.90,20,15.34,0,0,129,34,31
2997,2021-02-27,ST005,P010,Notebook,Stationery,36.48,20,128.94,0,1,59,31,38
2998,2021-02-28,ST005,P010,Notebook,Stationery,42.54,5,30.74,0,1,70,38,34
2999,2021-03-01,ST005,P010,Notebook,Stationery,40.31,10,109.23,0,0,37,34,21

In [4]:
df.head()

,Date,Store_ID,Product_ID,Product_Name,Category,Price,Discount_Percent,Advertising_Spend,Holiday_Flag,Weekend_Flag,Stock_Available,Previous_Day_Sales,Units_Sold
0,2021-01-01,ST001,P001,Rice 5kg,Grocery,659.32,0,174.34,0,0,44,15,12
1,2021-01-02,ST001,P001,Rice 5kg,Grocery,591.69,10,32.03,0,1,28,12,14
2,2021-01-03,ST001,P001,Rice 5kg,Grocery,661.10,0,160.97,0,1,94,14,14
3,2021-01-04,ST001,P001,Rice 5kg,Grocery,606.73,5,206.91,0,0,79,14,15
4,2021-01-05,ST001,P001,Rice 5kg,Grocery,581.60,10,242.67,0,0,79,15,16

In [5]:
df.tail()

,Date,Store_ID,Product_ID,Product_Name,Category,Price,Discount_Percent,Advertising_Spend,Holiday_Flag,Weekend_Flag,Stock_Available,Previous_Day_Sales,Units_Sold
2995,2021-02-25,ST005,P010,Notebook,Stationery,38.73,15,89.81,0,0,135,30,34
2996,2021-02-26,ST005,P010,Notebook,Stationery,35.90,20,15.34,0,0,129,34,31
2997,2021-02-27,ST005,P010,Notebook,Stationery,36.48,20,128.94,0,1,59,31,38
2998,2021-02-28,ST005,P010,Notebook,Stationery,42.54,5,30.74,0,1,70,38,34
2999,2021-03-01,ST005,P010,Notebook,Stationery,40.31,10,109.23,0,0,37,34,21

In [6]:
df.describe()

,Price,Discount_Percent,Advertising_Spend,Holiday_Flag,Weekend_Flag,Stock_Available,Previous_Day_Sales,Units_Sold
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,145.668207,5.950000,134.329253,0.008000,0.300000,87.153000,27.724000,27.830333
std,163.465689,6.724029,77.874095,0.089099,0.458334,41.200276,12.614867,12.632976
min,23.630000,0.000000,0.040000,0.000000,0.000000,15.000000,4.000000,4.000000
25%,55.570000,0.000000,67.717500,0.000000,0.000000,52.000000,18.000000,19.000000
50%,96.080000,5.000000,134.820000,0.000000,0.000000,87.000000,24.000000,24.000000
75%,142.580000,10.000000,197.975000,0.000000,1.000000,123.000000,34.000000,34.000000
max,662.940000,20.000000,324.900000,1.000000,1.000000,159.000000,95.000000,95.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                3000 non-null   object
 1   Store_ID            3000 non-null   object
 2   Product_ID          3000 non-null   object
 3   Product_Name        3000 non-null   object
 4   Category            3000 non-null   object
 5   Price               3000 non-null   float64
 6   Discount_Percent    3000 non-null   int64
 7   Advertising_Spend   3000 non-null   float64
 8   Holiday_Flag        3000 non-null   int64
 9   Weekend_Flag        3000 non-null   int64
 10  Stock_Available     3000 non-null   int64
 11  Previous_Day_Sales  3000 non-null   int64
 12  Units_Sold          3000 non-null   int64
dtypes: float64(2), int64(6), object(5)
memory usage: 304.8+ KB

In [8]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score

In [ ]:

from sklearn.preprocessing import LabelEncoder

# Instantiate encoders for text features
le_product = LabelEncoder()
le_category = LabelEncoder()

# Encode categorical variables
df['Product_Name_Encoded'] = le_product.fit_transform(df['Product_Name'])
df['Category_Encoded'] = le_category.fit_transform(df['Category'])

# Select features (ensuring correct names and removing hidden tab characters)
features = [
    'Product_Name_Encoded', 'Category_Encoded', 'Price', 'Discount_Percent',
    'Advertising_Spend', 'Holiday_Flag', 'Weekend_Flag', 'Stock_Available', 'Previous_Day_Sales'
]

x = df[features]
y = df['Units_Sold']

# Train the Random Forest Regressor
model = RandomForestRegressor(n_estimators=150, random_state=42)
model.fit(x, y)

y_pred = model.predict(x)
r2 = r2_score(y, y_pred)
print(f"Model trained successfully! R2 score: {r2:.4f}")

# Get user inputs and encode them correctly before predicting
pro = input("enter the product name (e.g., Rice 5kg): ")
cat = input("enter the category (e.g., Grocery): ")
pri = float(input("enter the price: "))
dis = float(input("enter the discount: "))
adv = float(input("enter the advertising: "))
hol = float(input("enter the holiday (0 or 1): "))
wee = float(input("enter the weekend (0 or 1): "))
sto = float(input("enter the stock: "))
pre = float(input("enter the previous day sales: "))

# Encode user inputs using the fitted LabelEncoders
try:
    pro_encoded = le_product.transform([pro])[0]
    cat_encoded = le_category.transform([cat])[0]

    # Predict
    pred = model.predict([[pro_encoded, cat_encoded, pri, dis, adv, hol, wee, sto, pre]])
    print(f"Predicted Units Sold: {int(pred[0])}")